baseurl = "https://www.dementyev.me"
title = "Eugene Dementyev's personal website"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Eugene Dementyev"
  info = "A DevOps, engineer and home automation enthusiast"
  description = "Eugene Dementyev's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 1986

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# analytics
[params.cloudflare]
  token = "ef681aea42d8472bb573ac7f724834ff"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ekini/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/ekini/"
[[params.social]]
  name = "Matrix"
  icon = "fa fa-matrix-org fa-2x"
  weight = 3
  url = "https://matrix.to/#/@ekini:ekini.info"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
